namespace GetTheMilk.Actions.BaseActions
{
    public enum ActionType
    {
        Default,
        Communicate,
        Attack,
        Buy,
        EnterLevel,
        ExposeInventory,
        GiveTo,
        Keep,
        Kick,
        Meet,
        Quit,
        Run,
        Sell,
        TakeFrom,
        TakeMoneyFrom,
        Teleport,
        Walk,
        Open,
        InitiateHostilities,
        SelectDefenseWeapon,
        SelectAttackWeapon,
        AcceptQuit,
        CloseInventory,
        Defuse
    }
}
